name: Expenses_app
description: App for tracking personal expenses.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # icons
  cupertino_icons: ^0.1.3
  flutter_icons: ^1.1.0

  # data class helpers
  equatable: ^1.2.6
  flutter_hooks: null

  # state management
  stacked: ^1.7.6
  stacked_services: ^0.6.0+1
  get_it: ^5.0.1

  # storage
  sqflite: ^1.3.2+1
  sqflite_migration_service: ^1.0.4

  # ui
  animations: ^1.1.1
  charts_flutter: ^0.9.0
  flutter_datetime_picker: ^1.4.0
  multi_select_flutter: ^3.1.2

  # other
  auto_route: ^0.6.9
  intl: ^0.16.1
  jiffy: ^3.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: null
  build_runner: null
  mockito: null

flutter:
  uses-material-design: true

  assets:
    - assets/sql/
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 900